apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: cronjob-daemonset-access-role
  namespace: {{ .Values.worker.namespace }}
rules:
- apiGroups:
  - "apps"
  - ""
  resources:
  - daemonsets
  - pods
  - jobs
  - cronjobs
  - secrets
  - pods/log
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: cronjob-daemonset-access-rolebinding
  namespace: {{ .Values.worker.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cronjob-daemonset-access-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.worker.namespace }}
{{ if ne .Values.worker.namespace .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: cronjob-daemonset-access-rolebinding2
  namespace: {{ .Values.worker.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cronjob-daemonset-access-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
{{ end }}