kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
{{ if ne .Values.worker.namespace .Values.namespace }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.worker.namespace }}
{{ end }}