apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: imagecleanup
  namespace: {{ .Values.namespace }}
  labels:
    app: imagecleanup
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: imagecleanup
  template:
    metadata:
      labels:
        name: imagecleanup
    spec:
      hostNetwork: true
      containers:        
        # MDSD
        - name: cleanup
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ if .Values.image.tag }}{{ .Values.image.tag }}{{ else }}{{ .Files.Get "version" }}{{ end }}
          volumeMounts:
            - name: containerdsock
              mountPath: /var/run/containerd/containerd.sock
              readOnly: true
          {{- if .Values.waittime }}
          env:
          - name: "CLEAN_WAIT"
            value: {{ .Values.waittime | quote }}
          {{- end }}
      volumes:
        - name: containerdsock
          hostPath:
            path: /var/run/containerd/containerd.sock