valuesFile: values.yaml

#the namespace to deploy the job to
namespace: azure-cleanup

# the job image details
image:
  registry: registry.hub.docker.com/disi33
  name: image-cleanup-job
  tag: "latest"

worker:
  image:
    # the registry to pull the worker image from
    registry: registry.hub.docker.com/disi33
    # the worker image name (defaults to 'image-cleanup-worker')
    name: image-cleanup-worker
    # the worker image tag (defaults to the latest available version number as of this release - NOT latest)
    tag: latest
  # the time to wait before starting cleanup to allow ongoing image pulls to finish in seconds (max. 120s - defaults to 120s)
  waittime: 15
  # the namespace to run the image in (defaults to 'image-cleanup')
  namespace: azure-cleanup

